### PR TITLE
[WIP] Add method to get history of a specific file

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This is a naive implementation of a "get history of a single file" (as discussed in #529 and shown in #343) and I'm seeking for feedback here.

I didn't add tests because I don't know how to approach this and I'd be happy about improvement suggestions and the like!

### CODE REVIEW

**Comment by arthurschreiber** [comment]
Hey @matthiasbeyer

Thanks for the contribution! I'm not sure how to proceed here, as this is something we want in libgit2, and not come up with our own implementation in Rugged. Also, your solution, as you pointed out, is quite naive and does not provide more advanced functionality that `git log` would support (like rename detection). I'd rather not take in an implementation that'll later differ from what libgit2 is going to provide in the future.

**Comment by matthiasbeyer** [comment]
Hi!

Are there plans for this in libgit2? So well... Then I'll implement it in my application until it is provided through libgit2, of course!

Anyways, this is a really nice library and I really enjoy using it. The docs could use some polishing, but well... nothing is perfect! Thanks for developing it!

**Comment by arthurschreiber** [comment]
@carlosmn has been talking about implementing this for a long time now, but the problem is that a "correct" implementation will be everything but trivial.

There's a feature in git that is eliminiating intermediate commits if you do a git log filtered by a path, and libgit2 will have to implement something similar to match the results of git. Unfortunately, libgit2 can't take the same approach that git is using to perform this elimination.

But I can promise you once it has landed in libgit2, it will also be available through rugged. :smile:

**Comment by carlosmn** [comment]
I've largely been thinking about how inappropriate the current API is to return this kind of data. There is libgit2/libgit2#3041 to track which features we want to add. The revwalk itself just isn't enough to do anything with history simplification, which path filtering would need.

Also note that while giving a list of commits which touch a file might be what you want to do sometimes, this is not enough to provide an API we'd be happy with. With an implementation such as this, you do not have the information necessary for something like `git log --graph`. You may want to throw it away, but rugged should be providing it.

There's also the issue that "history_of_file" is an inaccurate way to describe what's happening. The file doesn't exist as an entity. What this is doing is filtering by the path. If a file at a particular path is removed and then re-appears, we don't know that it's the same file (and e.g. Subversion would consider this to be two different files, whereas git would show it).

**Pull request closed without merging**
