### PR TITLE
Merge master into maintenance branch and bump version

### PR DESCRIPTION
**Pull request by dometto**
Please see #818. New versions have been created off the `maint/v0.28` branch (and its counterpart for `v0.27`), causing new features and fixes in `master` from the past year to be absent in new releases. This PR merges `master` into `maint/v0.28` and bumps the `rugged` version. It would be great if this could be merged, and a new release be made on the basis of it.

cc @tenderlove @vmg @carlosmn

### CODE REVIEW

**Comment by dometto** [comment]
Test failure seems to be due to a failure to setup ruby 2.3.7 on Linux on the CI.

**Comment by ethomson** [comment]
> New versions have been created off the maint/v0.28 branch (and its counterpart for v0.27), causing new features and fixes in master from the past year to be absent in new releases.

v0.28 and v0.27 are maintenance branches, so they only get bugfixes.  What you've described is the appropriate behavior for them - they shouldn't be getting entirely new features from master.

> This PR merges master into maint/v0.28 and bumps the rugged version. It would be great if this could be merged, and a new release be made on the basis of it.

I'd encourage you instead to create a PR against master that revs the version to 0.29, as a new release branch.  I think that makes sense as the path forward for master instead of trying to backport new features into maintenance branches.

**Comment by dometto** [comment]
@ethomson thanks for the switft reply. Happy to do so, but would that mean we would have to wait until `libgit2 v.029` is released? If so, can you give an approximate indication of when that would be?

**Comment by ethomson** [comment]
Well, that is a good question.  I'm sorry, I hadn't realized that rugged tracked libgit2's releases in that way -- I'm not very familiar with rugged since I'm not much of a rubyist.  Though it does make sense.

libgit2 is preparing for an 0.99.  We have - in my mind - two issues left that I'd like to tackle before we do that.  We'll use this as a bugfix/stabilization release leading up to 1.0.

It might make sense for rugged to do an 0.99 prerelease instead of an 0.29?  That way it's a) pulling in the latest libgit2 bits, but not b) doing a full release ahead of the libgit2 release.

Maybe it would be called 0.29 prerelease, I'm not sure what makes the most sense here.

**Comment by dometto** [comment]
> It might make sense for rugged to do an 0.99 prerelease instead of an 0.29? That way it's a) pulling in the latest libgit2 bits, but not b) doing a full release ahead of the libgit2 release.

If the rugged maintainers are prepared to do such a prerelease, that would be great! I'd happy to open a PR that pulls in the relevant bits of libgit2 and is based on rugged `master`. @ethomson what commit in libgit2 would you recommend pulling in for this? The current HEAD, i.e. a76348ee88c2ab4f079491f0a3810a12592b95cb?

**Comment by dometto** [comment]
I see libgit2 v0.99 has just been released. @carlosmn what are the chances of incorporating the changes to rugged `master` in the (I assume) upcoming corresponding release of rugged?

**Pull request closed without merging**
