### PR TITLE
Allow Windows to optionally use pkg-config if it's available.

### PR DESCRIPTION
**Pull request by mscharley**
My attempt at a solution to #558. This build a working gem with a vendored libgit2 installation with or without libssh2 as available on Windows.

### CODE REVIEW

**Comment by mscharley** [comment]
Bah, ignore the above. If you don't fully uninstall the gem before reinstalling it then gem doesn't actually update the `rugged.so` correctly despite wasting time compiling it again. The attached code works perfectly on Windows to allow linking libssh2 via pkg-config if it's available.

**Comment by arthurschreiber** [comment]
@mscharley Can you try out the changes in the `arthur/build-with-libssh2-windows` branch? c31cce77dc embdes libssh2 into libgit2 by making use of a special build option of libgit2. I'd prefer this solution over yours as it does not require `pkg-config`.

**Comment by mscharley** [comment]
I'll test out your branch a bit later. Is there any reason to limit it to Windows though? Specifically, on OSX I had issues when I first started using rugged because I didn't realise that libssh2 was an optional dependency so I couldn't actually use the first version of the gem I downloaded.

**Comment by arthurschreiber** [comment]
@mscharley I just force pushed a new change to my branch. https://github.com/libgit2/rugged/commit/9481db33e5c76ce16bc5fc84313572bb8f89bcc9 will automatically download and build `pkg-config-lite` on windows and will also download and build a static version of libssh2. It's working for me on my machine:

```
[rugged] main> RUBY_PLATFORM
=> "i386-mingw32"
[rugged] main> Rugged.features
=> [:threads, :https, :ssh]
[rugged] main>
```

There's no reason to not enable this on other platforms besides windows, it'll come later. :smile:

**Comment by mscharley** [comment]
I had a quick look and it definitely looks reasonable. I'll have to leave testing it here till the morning though, it's way too late already.

**Comment by mscharley** [comment]
No go. Final linking step:

```
C:\Ruby22-x64\lib\ruby\gems\2.2.0\gems\rugged-0.24.0b11\ext\rugged $ make
linking shared-object rugged/rugged.so
x86_64-w64-mingw32-gcc -shared -s -o rugged.so rugged.o rugged_backend.o rugged_blame.o rugged_blob.o rugged_branch.o rugged_branch_collection.o rugged_commit.o rugged_config.o rugged_cred.o rugged_diff.o rugged_diff_delta.o rugged_diff_hunk.o rugged_diff_line.o rugged_index.o rugged_note.o rugged_object.o rugged_patch.o rugged_reference.o rugged_reference_collection.o rugged_remote.o rugged_remote_collection.o rugged_repo.o rugged_revwalk.o rugged_settings.o rugged_signature.o rugged_submodule.o rugged_submodule_collection.o rugged_tag.o rugged_tag_collection.o rugged_tree.o -LC:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rugged-0.24.0b11/ext/rugged/../../vendor/libgit2/build -L. -L/C/Ruby22-x64/lib -L.  -LC:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rugged-0.24.0b11/vendor/libgit2/build/ports/x86_64-w64-mingw32/libssh2/1.6.0/lib -LC:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rugged-0.24.0b11/vendor/libgit2/build/deps/winhttp -Wl,--enable-auto-image-base,--enable-auto-import rugged-x64-mingw32.def    -lx64-msvcrt-ruby220 -lgit2  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi
-lwinhttp -lcrypt32 -lrpcrt4 -lole32 -lgit2 -lssh2 -lws2_32 -lbcrypt -lcrypt32
c:/ruby22-x64/devkit-mingw64-64-4.7.2/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.7.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lssh2
collect2.exe: error: ld returned 1 exit status
make.exe": *** [rugged.so] Error 1
```

Specifically, it's trying to pull libssh2 from `-LC:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rugged-0.24.0b11/vendor/libgit2/build/ports/x86_64-w64-mingw32/libssh2/1.6.0/lib` but it's actually in `C:\Ruby22-x64\lib\ruby\gems\2.2.0\gems\rugged-0.24.0b11\ext\rugged\ports\x86_64-w64-mingw32\libssh2\1.6.0\lib`

**Comment by mscharley** [comment]
Got it working with this patch: [`835be6c`](https://github.com/mscharley/rugged/commit/835be6cb77477f6504ddc19570571c6d01bfb679) See also the small patch to libgit2 that's needed attached the comments on that commit.

**Comment by mscharley** [comment]
```
irb(main):001:0> RUBY_PLATFORM
=> "x64-mingw32"
irb(main):002:0> require 'rugged'
=> true
irb(main):003:0> Rugged.features
=> [:threads, :https, :ssh]
irb(main):004:0>
```

**Comment by ethomson** [comment]
@mscharley That patch to libgit2 seems reasonable, would you mind opening a PR over there?  Thanks!

**Comment by arthurschreiber** [comment]
I've a few more patches for libgit2 that'll clean up some additional things related to the pkg-config file that is generated for libgit2 and will open a PR shortly.

**Pull request closed without merging**
