### PR TITLE
Add appveyor config

### PR DESCRIPTION
**Pull request by carlosmn**
Not sure if it'll work, but let's find out.

### CODE REVIEW

**Comment by arthurschreiber** [comment]
See also https://github.com/libgit2/rugged/commit/6e449b5145458f2f87db516eb8e175b4481a894c.

**Comment by arthurschreiber** [comment]
And #462. The main issue I've been running into with AppVeyor builds is that the locking of files is a pain in the butt. I'm still struggling to come up with a good approach to fix that.

**Comment by carlosmn** [comment]
Oops, I forgot we already have one PR for that. The locking is indeed a pain. Have you thought about letting a user pass a block to the repository constructor, similarly to how you might use a file or temp directory?

**Comment by arthurschreiber** [comment]
@carlosmn Even adding a block by itself does not really help.

Something along the lines of:

```ruby
Rugged::Repository.open "some-repo" do |repo|
  # Do something with repo...
end
```

Won't fix the issue by itself. Due to the way GC in Ruby works, there's no guarantee that the repo object (or any of the objects created inside the block) will be collected by the time the block is exited. Instead, we'll have to add APIs to explicitly close resources like `Repository` or `Index` instances, probably even more objects.

When such an object is created from a repository method, we need to track those in an array using `WeakRef`s inside the repo object, and close them as well as the repository object once the end of the block is reached. That's how e.g. file handles work (and are limited in their livetime).

I started adding this functionality inside https://github.com/libgit2/rugged/commit/6c9af54a68fb7791230469936cfef4d02abbbe60, but I'm not too happy with that solution.

**Comment by vmg** [comment]
Hmmm... Can we remove Appveyor altogether here? It seems like quite a big maintenance burden; we don't use Rugged on Windows, we don't officially support it on Windows and afaik we don't have any Windows experts to take care and maintain this kind of stuff. So at this point it feels like throwing in an extra build that keeps failing and will continue to do so for the foreseeable future.

**Comment by arthurschreiber** [comment]
Yeah, I'm afraid that just disabling the AppVeyor build and throwing away the work I made in the win32 PR is probably going to be the best way to proceed here.

I'd be really happy to see Rugged support for windows, but I don't want to add all the complexity to the code base to make it work. :disappointed:

**Comment by carlosmn** [comment]
Not supporting Windows is fine by me too. As you point out, we don't have anybody who would know or care to keep it compatible.

I've deactivated the hook so we won't ask appveyor to build rugged anymore.

**Comment by nulltoken** [comment]
@carlosmn @arthurschreiber Should I drop the repo from the AppVeyor config as well?

**Comment by vmg** [comment]
> throwing away the work I made in the win32 PR is probably going to be the best way to proceed here.

Throwing away work always sucks, but in this case it's more like saving you work on the long run. Windows is a tricky beast, and Ruby extensions on Windows doubly so. :)

Thank you so much for the effort!

**Pull request closed without merging**
