### PR TITLE
Update to latest libgit2

### PR DESCRIPTION
**Pull request by arthurschreiber**
This updates to the latest libgit2 version. There is a single test failure, but that will be fixed once #469 gets merged.

This closes #468.

//cc @vmg @simonsj

### CODE REVIEW

**Comment by vmg** [comment]
Looking very nice. Thanks for rushing this @arthurschreiber!

Random question, now that are these signature APIs are gone, how do you pass signatures around? Are there other APIs we haven't wrapped yet that do this? cc @carlosmn

**Comment by carlosmn** [comment]
The default signature will be taken from the environment, just like git does. If you want to override the signature, you can call `git_repository_set_iden()` and we'll use that.

**Comment by arthurschreiber** [comment]
I don't think this function is bound yet. I'll get to it later today.

**Comment by vmg** [comment]
@arthurschreiber: Can you fix the test and then go ahead and merge? Thanks!

**Comment by arthurschreiber** [comment]
I just rebased this against the latest master, which should fix the test failure.

**Comment by arthurschreiber** [comment]
:heart:

**Comment by vmg** [comment]
:+1::+1:

**Comment by adelcambre** [comment]
Thanks @arthurschreiber! Can you release a new beta on rubygems? Thanks!

**Pull request merged**
