### PR TITLE
Fix failing online test cases

### PR DESCRIPTION
**Pull request by arthurschreiber**
~~~Looks like someone changed https://github.com/libgit2/TestGitRepository.git.~~~

See @nulltoken's comment below.

### CODE REVIEW

**Comment by nulltoken** [comment]
Nope. See https://github.com/libgit2/libgit2sharp/pull/995

**Comment by arthurschreiber** [comment]
@nulltoken Oh, thanks for pointing this out!

**Comment by nulltoken** [comment]
How come AppVeyor isn't listed above?

**Comment by arthurschreiber** [comment]
That hasn't been working correctly for some while now. I think builds get triggered, but the commit status is not correctly send back to github.

**Comment by arthurschreiber** [comment]
To be more correct, this has not been working, ever. :smile:

**Comment by FeodorFitsner** [comment]
I see these messages in AV logs:
```
Error setting gitHub repository 'libgit2/libgit2sharp.nativebinaries' status (buildId=606616): Response status code does not indicate success: 404 (Not Found)
HTTP POST to https://api.github.com/repos/libgit2/libgit2sharp.nativebinaries/statuses/cb5d59b070084ad83e70b552a5bedf41a10b1338 returned 404: Not Found;
```

which basically means (403 forbidden) in terms of GitHub API - currently authorized GH user in AppVeyor doesn't have permissions to write commit status.

**Comment by arthurschreiber** [comment]
Why is AV trying to send a status update to the libgit2sharp.nativebinaries repo for a build on the rugged repo? Is something setup incorrectly on our side?

**Comment by FeodorFitsner** [comment]
Same messages for rugged (sorry, posted wrong messages in the first place)
```
HTTP POST to https://api.github.com/repos/libgit2/rugged/statuses/6f8b38042a02174c24ee6a3857b70faa0a29688a
Error setting gitHub repository 'libgit2/rugged' "pending" status (buildId=609259): Response status code does not indicate success: 404 (Not Found)
```

**Comment by nulltoken** [comment]
>which basically means (403 forbidden) in terms of GitHub API - currently authorized GH user in AppVeyor doesn't have permissions to write commit status.

@FeodorFitsner Thanks for that. How can we easily fix that?

**Comment by FeodorFitsner** [comment]
Login to AppVeyor, `libgit2` account, then open https://ci.appveyor.com/account to check what GH account is currently authorized. Make sure that account has write permissions on `libgit2/rugged` and `libgit2/libgit2sharp.nativebinaries` repos.

**Comment by nulltoken** [comment]
@FeodorFitsner Thanks to you we've been able to understand the root cause of the issue. Hopefully, the problem should be solved now.

**Pull request merged**
