### PR TITLE
Fix misprint and incorrect formatting + remove obsolete license headers

### PR DESCRIPTION
**Pull request by apoluektov**

### CODE REVIEW

**Comment by arthurschreiber** [comment]
@vmg Do we want to remove the copyright notices from the individual c files?

**Comment by ethomson** [comment]
There probably shouldn't be _nothing_.

I concede that changing the date is quite obnoxious.  What libgit2 did here (a brief, dateless copyright blurb) seems like the least common denominator that lawyers and devs seem happy with.

**Comment by apoluektov** [comment]
But what is the difference between rugged *.rb and *.c files regarding to this issuse? Why the former don't require the copyright notices but the latter do?

I though as long as the LICENSE file is here, and its content is identical to the copyright notice, there were no need to repeat it in the individual files... Am I wrong?

**Comment by ethomson** [comment]
IANAL, but there's no explicit _requirement_ per se.  Speaking generally, a few lines at the top of one source file isn't necessary, rugged is copyrighted regardless.

My suggestion would be:
1. Create a brief statement.
2. Omit date and specific copyright owners from this statement, since those are the things that might need changing.  (And either require maintenance or suggest obsolescence.)
3. Apply it to all the source files, be they C or Ruby.

Modifying the libgit2 blurb would give us:
```
/*
 * Copyright (C) the Rugged contributors.  All rights reserved.
 *
 * This file is part of Rugged, distributed under the MIT license.
 * For full terms see the included LICENSE file.
 */
```

**Comment by apoluektov** [comment]
Ok, sounds great!

If there are no other objections, I'll proceed with that.

**Comment by apoluektov** [comment]
Done. I hope we don't need to add those headers to tests/scripts :)

**Comment by apoluektov** [comment]
bump

**Comment by vmg** [comment]
Looking good! Thanks for the cleanup :)

**Pull request merged**
